# Inserts a blank line between shell prompts
add_newline = false
command_timeout = 3000

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[](bold blue)[](bold bright-blue)[](bold cyan)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold bright-red)[](bold red)[](bold bright-yellow)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
vimcmd_symbol = "[*](bold white)[*](bold white)[*](bold white)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true
